name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php-version: [8.2]

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, dom, curl
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate key
        run: php artisan key:generate

      - name: Directory permissions
        run: |
          chmod -R 777 storage
          chmod -R 777 bootstrap/cache

      - name: Run tests
        run: php artisan test
  phpstan:
    runs-on: ubuntu-latest
    needs: phpunit
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, curl
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPStan
        run: echo "Running PHPStan"

  deploy:
    runs-on: ubuntu-latest
    needs: phpunit
    if: success()
    steps:
      - name: Deploy to production
        run: echo "Deploy to production"

