name: Update Pull Request Description

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Pull Request Description
        run: |
          MESSAGE=$(cat ./.github/pull_request_template.md)
          echo "${MESSAGE}"
