name: Update Pull Request Description

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read message from file
        id: read-message
        run: |
          MESSAGE=$(cat ./.github/pull_request_template.md)
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "$MESSAGE"
          echo "$PR_NUMBER"
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT

      - name: Update Pull Request Description
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          MESSAGE="${{ steps.read-message.outputs.message }}"

          echo $MESSAGE

          # Update pull request description using GitHub API
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$MESSAGE\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER"
