name: Update Pull Request Description

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.1
        with:
          content: "<!-- start regex match -->New content!<!-- end regex match -->"
          regex: "<!-- start regex match -->.*?<!-- end regex match -->"
          regexFlags: ims
          token: ${{ secrets.GH_TOKEN }}
