name: Update Pull Request Description

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Pull Request Description
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          MESSAGE=$(cat ./.github/pull_request_template.md)
          MESSAGE="${MESSAGE_TEMPLATE/PR_NUMBER/$PR_NUMBER}"

          echo "${MESSAGE}"
