name: Update Pull Request Description

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  update-description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update PR Description
        uses: nefrob/pr-description@v1.1.1
        with:
          content: "{PR_NUMBER}11111{/PR_NUMBER}"
          regex: "{PR_NUMBER}.*?{/PR_NUMBER}"
          regexFlags: ims
          token: ${{ secrets.GH_TOKEN }}
